package com.example.quhizz;


public class QuestionsAndAnswers {
    public static class Math{
        public static String questions[] = {
                "What is the result of 5 + 7?",
                "Simplify the expression: 3x + 2x",
                "If a triangle has angles of 90 degrees, 45 degrees, and x degrees, what is the value of x?",
                "Solve for x: 2x + 5 = 15",
                "What is the perimeter of a rectangle with a length of 8 units and a width of 6 units?",
                "If you roll a fair six-sided die, what is the probability of rolling a 3 or a 4?",
                "What is the solution to the equation 2x - 3 = 7?",
                "Find the area of a right triangle with a base of 10 units and a height of 6 units.",
                "If you have a right circular cone with a radius of 4 cm and a height of 8 cm, what is the volume of the cone?",
                "What is the value of π (pi) to three decimal places?",
                "Simplify the expression: 4(2x - 3)",
                "Solve for x: 3x + 6 = 12",
                "What is the square root of 81?",
                "If a car travels at a speed of 50 miles per hour for 4 hours, how far does it travel?",
                "What is the slope-intercept form of a linear equation?",
                "What is the solution to the equation 5(x - 2) = 15?",
                "What is the area of a circle with a radius of 5 cm?",
                "If you have $500 and you spend $150, how much money do you have left?",
                "What is the solution to the equation 2(x + 3) = 10?",
                "Simplify the expression: 2(3x - 4) - (x + 5)",
                "What is the value of sin(30°)?",
                "In a right triangle, if the length of one leg is 6 units and the hypotenuse is 10 units, what is the length of the other leg?",
                "If you flip a fair coin, what is the probability of getting tails?",
                "What is the median of the following set of numbers: 5, 8, 4, 12, 7, 6?",
                "What is the solution to the equation 4x - 5 = 7?",
                "Find the volume of a rectangular prism with length 9 cm, width 5 cm, and height 3 cm.",
                "Simplify the expression: (2x + 3)(3x - 4)",
                "What is the value of cos(60°)?",
                "If a box contains 36 marbles, and you take out 12, how many marbles are left in the box?",
                "What is the perimeter of a square with sides of length 9 units each?",
                "If you multiply 3/4 by 2/5, what is the result?",
                "Solve for x: 2x/3 = 8",
                "Find the area of a parallelogram with a base of 12 units and a height of 8 units.",
                "What is the solution to the equation 3(2x - 1) = 15?",
                "If you have $250 and you want to give 10% as a tip, how much should you tip?",
                "What is the value of tan(45°)?",
                "In a right triangle, if one acute angle is 30°, what is the measure of the other acute angle?",
                "If you have a box with 24 colored pencils, and 1/3 of them are red, how many colored pencils are red?",
                "What is the solution to the equation 5x/2 = 15?",
                "Find the volume of a cylinder with a radius of 6 cm and a height of 10 cm.",
        };

        public static String choices[][] = {
                {"12", "13", "14", "15"},
                {"5x", "6x", "7x", "8x"},
                {"45 degrees", "60 degrees", "30 degrees", "90 degrees"},
                {"x = 5", "x = 6", "x = 7", "x = 8"},
                {"28 units", "32 units", "36 units", "40 units"},
                {"1/3", "1/2", "1/6", "1/12"},
                {"x = 5", "x = 6", "x = 7", "x = 8"},
                {"30 square units", "45 square units", "60 square units", "90 square units"},
                {"134.52 cm³", "150.72 cm³", "201.12 cm³", "402.24 cm³"},
                {"3.142", "3.141", "3.140", "3.139"},
                {"8x - 12", "8x - 3", "8x - 7", "8x + 12"},
                {"x = 2", "x = 3", "x = 4", "x = 5"},
                {"7", "8", "9", "10"},
                {"200 miles", "250 miles", "300 miles", "350 miles"},
                {"y = mx + b", "y = ax^2 + bx + c", "y = 2x + 1", "y = -3x + 2"},
                {"x = 3", "x = 4", "x = 5", "x = 6"},
                {"78.54 cm²", "94.2 cm²", "110.88 cm²", "125.66 cm²"},
                {"$350", "$400", "$450", "$550"},
                {"x = 1", "x = 2", "x = 3", "x = 4"},
                {"5x - 8", "5x - 3", "5x - 10", "5x + 9"},
                {"0.5", "0.6", "0.3", "0.4"},
                {"√19", "√34", "√64", "√100"},
                {"0.5", "1.0", "2.0", "2.5"},
                {"1/4", "1/3", "1/2", "3/4"},
                {"1/2", "1", "2/3", "4/3"},
                {"2", "4", "6", "8"},
                {"3.464", "5.196", "4.321", "6.247"},
                {"24 marbles", "12 marbles", "20 marbles", "18 marbles"},
                {"36 units", "27 units", "18 units", "9 units"},
                {"3/8", "6/7", "1/2", "4/5"},
                {"x = 12", "x = 24", "x = 16", "x = 8"},
                {"$10", "$25", "$5", "$15"},
                {"1", "√2", "2", "√3"},
                {"45 degrees", "60 degrees", "75 degrees", "90 degrees"},
                {"2/3", "1/3", "1/6", "3/4"},
                {"x = 12", "x = 24", "x = 16", "x = 8"},
                {"$25", "$50", "$75", "$100"},
                {"1", "0.5", "√2", "2"},
                {"45 degrees", "60 degrees", "75 degrees", "90 degrees"},
                {"8", "16", "12", "24"},
                {"x = 20", "x = 15", "x = 10", "x = 5"},
                {"188.4 cm³", "226.08 cm³", "282.6 cm³", "564.12 cm³"},
        };

        public static String correctAnswers[] = {
                "12",
                "5x",
                "45 degrees",
                "x = 5",
                "28 units",
                "1/3",
                "x = 5",
                "30 square units",
                "201.12 cm³",
                "3.142",
                "8x - 12",
                "x = 2",
                "9",
                "200 miles",
                "y = mx + b",
                "x = 3",
                "78.54 cm²",
                "$400",
                "x = 1",
                "5x - 8",
                "0.5",
                "√64",
                "2.5",
                "1/2",
                "2",
                "5.196",
                "12 marbles",
                "36 units",
                "6/7",
                "x = 8",
                "$25",
                "√2",
                "45 degrees",
                "1/6",
                "x = 8",
                "$15",
                "1",
                "45 degrees",
                "12",
                "x = 5",
                "226.08 cm³",
        };
    }


    public static class Science {
        public static String questions[] = {
                "What is the chemical symbol for water?",
                "What is the primary function of the mitochondria?",
                "What is the smallest planet in our solar system?",
                "What gas do plants absorb from the atmosphere during photosynthesis?",
                "What is the process by which plants make their own food?",
                "What is the most abundant gas in Earth's atmosphere?",
                "What is the atomic number of carbon?",
                "What is the largest organ in the human body?",
                "What is the chemical symbol for gold?",
                "What is the study of earthquakes called?",
                "What is the main component of the Earth's core?",
                "What is the process of a liquid turning into a gas called?",
                "What is the chemical symbol for oxygen?",
                "What is the closest star to Earth?",
                "What is the process of a gas turning into a liquid called?",
                "What is the Earth's outermost layer called?",
                "What is the SI unit of electric current?",
                "What is the process of the Earth's plates moving called?",
                "What is the largest planet in our solar system?",
                "What is the chemical formula for methane?",
                "What is the force that attracts two objects with mass toward each other?",
                "What is the study of heredity and genetic variation called?",
                "What is the chemical symbol for iron?",
                "What is the energy currency of cells?",
                "What is the process of a solid turning into a gas without passing through the liquid phase called?",
                "What is the chemical symbol for sodium?",
                "What is the first element on the periodic table?",
                "What is the study of the Earth's atmosphere and weather called?",
                "What is the largest mammal in the world?",
                "What is the chemical symbol for nitrogen?",
                "What is the chemical formula for water?",
                "What is the center of an atom called?",
                "What is the speed of light in a vacuum?",
                "What is the chemical symbol for carbon dioxide?",
                "What is the phenomenon where an object appears to change its position due to a shift in the observer's viewpoint called?",
                "What is the process of a liquid turning into a solid called?",
                "What is the chemical symbol for helium?",
                "What is the SI unit of temperature?",
                "What is the study of the Earth's physical structure and composition called?",
                "What is the chemical formula for table salt?",
                "What is the fundamental building block of all matter?",
                "What is the process of one organism capturing and consuming another for food called?",
                "What is the chemical symbol for silver?",
                "What is the force that opposes the motion of an object in a fluid called?",
                "What is the study of the behavior and properties of matter called?",
                "What is the chemical formula for sulfuric acid?",
                "What is the chemical symbol for potassium?",
                "What is the process of converting light energy into chemical energy in plants called?",
                "What is the chemical symbol for potassium?",
                "What is the process by which plants convert sunlight into energy?"
        };

        public static String choices[][] = {
                { "H2O", "CO2", "N2", "O2" },
                { "Energy production", "Cell division", "Photosynthesis", "Digestion" },
                { "Venus", "Earth", "Mars", "Mercury" },
                { "Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen" },
                { "Respiration", "Fermentation", "Photosynthesis", "Combustion" },
                { "Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen" },
                { "4", "6", "7", "8" },
                { "Heart", "Brain", "Liver", "Skin" },
                { "Go", "Gd", "Au", "Ag" },
                { "Geology", "Seismology", "Biology", "Astronomy" },
                { "Iron", "Silicon", "Nickel", "Magma" },
                { "Condensation", "Evaporation", "Sublimation", "Melting" },
                { "O2", "C", "H2O", "N2" },
                { "Proxima Centauri", "Sirius", "Venus", "Mars" },
                { "Deposition", "Evaporation", "Condensation", "Sublimation" },
                { "Crust", "Mantle", "Core", "Lithosphere" },
                { "Ampere", "Volt", "Ohm", "Watt" },
                { "Erosion", "Eruption", "Evolution", "Plate tectonics" },
                { "Saturn", "Jupiter", "Neptune", "Mars" },
                { "H2O", "CO2", "N2", "CH4" },
                { "Gravitation", "Friction", "Magnetism", "Inertia" },
                { "Geology", "Biology", "Genetics", "Botany" },
                { "Fe", "Si", "Au", "Ag" },
                { "ATP", "DNA", "RNA", "Glucose" },
                { "Evaporation", "Condensation", "Sublimation", "Fusion" },
                { "Na", "S", "H2O", "He" },
                { "Hydrogen", "Oxygen", "Carbon", "Helium" },
                { "Meteorology", "Geology", "Biology", "Chemistry" },
                { "Blue whale", "Elephant", "Giraffe", "Polar bear" },
                { "N2", "CO2", "O2", "H2" },
                { "H2O", "CO2", "N2", "CH4" },
                { "Nucleus", "Proton", "Neutron", "Electron" },
                { "300,000 km/s", "150,000 km/s", "500,000 km/s", "750,000 km/s" },
                { "CO2", "O2", "H2O", "N2" },
                { "Refraction", "Diffraction", "Parallax", "Gravity" },
                { "Evaporation", "Condensation", "Fusion", "Freezing" },
                { "He", "H2", "O2", "N2" },
                { "Celsius", "Kelvin", "Fahrenheit", "Rankine" },
                { "Geology", "Astronomy", "Chemistry", "Botany" },
                { "NaCl", "H2O", "CO2", "O2" },
                { "Atom", "Molecule", "Cell", "Element" },
                { "Photosynthesis", "Predation", "Reproduction", "Respiration" },
                { "Si", "Ag", "Fe", "Au" },
                { "Viscosity", "Gravity", "Friction", "Density" },
                { "Physics", "Chemistry", "Biology", "Geology" },
                { "H2SO4", "CO2", "HCl", "NH3" },
                { "K", "P", "S", "Na" },
                { "Photosynthesis", "Chemiosmosis", "Respiration", "Electron transport chain" },
                { "P", "K", "S", "Na" },
                { "Respiration", "Fermentation", "Photosynthesis", "Combustion" }
        };

        public static String correctAnswers[] = {
                "H2O",
                "Energy production",
                "Mercury",
                "Carbon dioxide",
                "Photosynthesis",
                "Nitrogen",
                "6",
                "Skin",
                "Au",
                "Seismology",
                "Iron",
                "Evaporation",
                "O2",
                "Proxima Centauri",
                "Condensation",
                "Mantle",
                "Ampere",
                "Plate tectonics",
                "Jupiter",
                "CH4",
                "Gravitation",
                "Genetics",
                "Fe",
                "ATP",
                "Sublimation",
                "Na",
                "H2",
                "Hydrogen",
                "Meteorology",
                "Blue whale",
                "N2",
                "H2O",
                "Nucleus",
                "300,000 km/s",
                "CO2",
                "Parallax",
                "Freezing",
                "He",
                "Kelvin",
                "Geology",
                "NaCl",
                "Atom",
                "Predation",
                "Ag",
                "Viscosity",
                "Physics",
                "H2SO4",
                "K",
                "Photosynthesis",
                "K",
                "Photosynthesis"
        };
    }


    public static class Technology {
        public static String questions[] = {
                "What does CPU stand for in computing?",
                "Which company is known for its iPhone and Mac products?",
                "What is the world's largest social media platform?",
                "What does HTML stand for in web development?",
                "Which programming language is often used for artificial intelligence and machine learning?",
                "What technology allows wireless communication between devices over short distances?",
                "Which search engine is the most widely used worldwide?",
                "What is the term for software that is distributed for free and the source code is openly available for modification?",
                "What does GPS stand for in navigation?",
                "Which company is famous for its Windows operating system?",
                "What is the most common programming language for creating web pages and web applications?",
                "What is the primary function of a modem?",
                "What is the largest online retailer in the world?",
                "Which company is known for its search engine and online advertising services?",
                "What does URL stand for in web addresses?",
                "What is the term for the practice of obtaining sensitive information by disguising as a trustworthy entity in electronic communication?",
                "Which operating system is developed by Apple Inc.?",
                "What technology standard allows data to be transmitted over a computer network?",
                "Which social media platform is limited to 140-character posts?",
                "What does SSL stand for in internet security?",
                "Which company is famous for its e-commerce and cloud computing services?",
                "What is the term for a program that replicates itself and spreads to other computers?",
                "Which programming language was created by Microsoft and is widely used for developing Windows applications?",
                "What is the term for the process of converting data into a secret code to protect it from unauthorized access?",
                "What is the primary function of a router in a computer network?",
                "Which company is known for its electric cars and renewable energy products?",
                "What is the term for a self-contained program that performs a specific function on a web page?",
                "What does IoT stand for in the context of smart devices and technology?",
                "Which video-sharing platform is owned by Google?",
                "What is the term for the use of technology to provide a real-world experience in a virtual environment?",
                "What does RAM stand for in computer memory?",
                "Which programming language is often used for developing mobile apps for Android devices?",
                "What is the term for a malicious software that encrypts files and demands a ransom for their release?",
                "What is the world's largest online encyclopedia?",
                "What does AI stand for in the context of advanced computer intelligence?",
                "Which social media platform is known for its professional networking and job searching?",
                "What is the term for a hardware or software-based security system used to authenticate users and prevent unauthorized access?",
                "What is the term for the practice of reusing or modifying existing software code for a new purpose?",
                "Which company is known for its gaming console, PlayStation?",
        };

        public static String choices[][] = {
                {"Central Processing Unit", "Central Process Unit", "Computer Processor Unit", "Central Process Unit"},
                {"Apple", "Microsoft", "Google", "Facebook"},
                {"Facebook", "Instagram", "Twitter", "LinkedIn"},
                {"HyperText Markup Language", "Hyperlink Text Markup Language", "High-Level Text Markup Language", "Hyper Transfer Markup Language"},
                {"Python", "Java", "C++", "JavaScript"},
                {"Bluetooth", "Wi-Fi", "NFC", "LTE"},
                {"Google", "Bing", "Yahoo", "DuckDuckGo"},
                {"Open Source Software", "Freeware", "Shareware", "Malware"},
                {"Global Positioning System", "Geographic Positioning System", "Global Pointing System", "Geographic Pointing System"},
                {"Microsoft", "Apple", "Google", "IBM"},
                {"Python", "Java", "JavaScript", "C++"},
                {"Transmit data", "Receive data", "Convert data", "Modulate data"},
                {"Amazon", "Alibaba", "eBay", "Walmart"},
                {"Google", "Facebook", "Microsoft", "Apple"},
                {"Uniform Resource Locator", "Universal Reference Location", "Universal Resource Link", "Unified Reference Locator"},
                {"Phishing", "Virus", "Spyware", "Hacking"},
                {"Windows", "iOS", "Android", "Linux"},
                {"Ethernet", "Bluetooth", "USB", "Wi-Fi"},
                {"Facebook", "Twitter", "LinkedIn", "Instagram"},
                {"Secure Sockets Layer", "Super Security Layer", "Simple Security Layer", "Safe Socket Layer"},
                {"Amazon", "Microsoft", "Alibaba", "Google"},
                {"Malware", "Firewall", "Virus", "Spyware"},
                {"Python", "Java", "C#", "Ruby"},
                {"Encryption", "Decryption", "Firewall", "Authorization"},
                {"Connect devices", "Provide internet access", "Filter web content", "Encrypt data"},
                {"Tesla", "Ford", "Toyota", "General Motors"},
                {"Applet", "Widget", "Script", "Plug-in"},
                {"Internet of Things", "Internet of Technology", "Internet of Trends", "Internet of Testing"},
                {"YouTube", "Vimeo", "Twitch", "Dailymotion"},
                {"Virtual Reality", "Augmented Reality", "Mixed Reality", "Virtual Environment"},
                {"Random Access Memory", "Read-Only Memory", "Redundant Array of Memory", "Runtime Application Memory"},
                {"Python", "JavaScript", "C++", "Java"},
                {"Ransomware", "Malware", "Spyware", "Virus"},
                {"Wikipedia", "Wikimedia", "Wikibooks", "Wikiversity"},
                {"Artificial Intelligence", "Advanced Internet", "Algorithmic Information", "Automated Integration"},
                {"LinkedIn", "Twitter", "Instagram", "Facebook"},
                {"Firewall", "Encryption", "Authentication", "Authorization"},
                {"Code Reuse", "Code Modification", "Code Refactoring", "Code Redundancy"},
                {"Sony", "Nintendo", "Microsoft", "Sega"},
        };

        public static String correctAnswers[] = {
                "Central Processing Unit",
                "Apple",
                "Facebook",
                "HyperText Markup Language",
                "Python",
                "Bluetooth",
                "Google",
                "Open Source Software",
                "Global Positioning System",
                "Microsoft",
                "JavaScript",
                "Modulate data",
                "Amazon",
                "Google",
                "Uniform Resource Locator",
                "Phishing",
                "iOS",
                "Ethernet",
                "Twitter",
                "Secure Sockets Layer",
                "Amazon",
                "Malware",
                "C#",
                "Encryption",
                "Connect devices",
                "Tesla",
                "Widget",
                "Internet of Things",
                "YouTube",
                "Virtual Reality",
                "Random Access Memory",
                "Java",
                "Ransomware",
                "Wikipedia",
                "Artificial Intelligence",
                "LinkedIn",
                "Authentication",
                "Code Reuse",
                "Sony",
        };
    }
    public static class History {
        public static String questions[] = {
                "Which Egyptian pharaoh is famous for his tomb in the Valley of the Kings?",
                "Who was the first emperor of the Roman Empire?",
                "What event marked the beginning of World War I?",
                "Who is known as the 'Father of the Indian Nation' and led the nonviolent resistance against British rule in India?",
                "Which ancient civilization built the city of Machu Picchu?",
                "What famous ship sank in 1912 on its maiden voyage, leading to a tragic loss of lives?",
                "The Industrial Revolution began in which country?",
                "Who was the founder of the Mongol Empire?",
                "The Magna Carta, signed in 1215, limited the power of which English monarch?",
                "In what year did Christopher Columbus first arrive in the Americas?",
                "Who wrote 'The Communist Manifesto' with Karl Marx?",
                "During which war did the Battle of Gettysburg take place?",
                "Who was the first woman to fly solo across the Atlantic Ocean?",
                "What event is often considered the starting point of the Great Depression in the United States?",
                "Which famous speech by Martin Luther King Jr. was delivered during the March on Washington for Jobs and Freedom in 1963?",
                "Who was the last Russian tsar before the Russian Revolution of 1917?",
                "Which ancient civilization is known for the creation of the first written code of laws, known as the Code of Hammurabi?",
                "What empire was ruled by Suleiman the Magnificent, known for his legal reforms and cultural achievements?",
                "Who was the first President of the United States?",
                "What is the name of the ship that carried the Pilgrims to the New World in 1620?",
                "Which World War II battle is often considered the turning point in the European theater?",
                "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
                "Which explorer is credited with circumnavigating the globe, proving that the Earth is round?",
                "In what year did the Berlin Wall fall, leading to the reunification of East and West Germany?",
                "Who was the first woman to win a Nobel Prize and remains the only person to win Nobel Prizes in two different scientific fields?",
                "What ancient city was destroyed by the eruption of Mount Vesuvius in 79 AD?",
                "Who wrote 'The Art of War,' an ancient Chinese military treatise?",
                "Which famous leader of the women's suffrage movement in the United States is known for her role in securing women's right to vote?",
                "During which war did the Battle of Stalingrad take place?",
                "What is the name of the ship that Charles Darwin sailed on during his voyage that led to the theory of evolution?",
                "Who is known for his voyages to the New World and is often credited with discovering America?",
                "What treaty officially ended World War I and was signed in 1919?",
                "Which English queen is known for her long and prosperous reign, which is often called the Elizabethan Era?",
                "Who was the Egyptian queen known for her relationship with Julius Caesar and Mark Antony?",
                "What is the term for the period of renewed interest in art, culture, and learning in Europe that began in the 14th century?",
                "Who was the first man to walk on the moon?",
                "Which American president is known for issuing the Emancipation Proclamation during the Civil War?",
                "Who was the famous nurse known as the 'Lady with the Lamp' during the Crimean War?",
                "In what year did the United States declare its independence from Great Britain?",
                "Which Chinese philosopher is associated with the philosophy of Confucianism?",
        };

        public static String choices[][] = {
                {"Tutankhamun", "Ramses II", "Cleopatra", "Hatshepsut"},
                {"Julius Caesar", "Augustus", "Nero", "Caligula"},
                {"Assassination of Archduke Franz Ferdinand", "Signing of the Treaty of Versailles", "Fall of Constantinople", "Russian Revolution"},
                {"Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel"},
                {"Mayans", "Aztecs", "Incas", "Olmecs"},
                {"RMS Lusitania", "RMS Titanic", "HMS Britannia", "SS Normandie"},
                {"France", "United Kingdom", "United States", "Germany"},
                {"Genghis Khan", "Kublai Khan", "Attila the Hun", "Tamerlane"},
                {"Henry II", "Richard the Lionheart", "King John", "Edward I"},
                {"1492", "1510", "1525", "1537"},
                {"Vladimir Lenin", "Joseph Stalin", "Friedrich Engels", "Leon Trotsky"},
                {"American Civil War", "World War I", "Mexican-American War", "War of 1812"},
                {"Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"},
                {"Stock Market Crash of 1929", "Prohibition", "Assassination of Archduke Franz Ferdinand", "Dust Bowl"},
                {"I Have a Dream", "Letter from Birmingham Jail", "I See the Promised Land", "The Ballot or the Bullet"},
                {"Nicholas II", "Peter the Great", "Ivan the Terrible", "Catherine the Great"},
                {"Sumerians", "Egyptians", "Babylonians", "Assyrians"},
                {"Ottoman Empire", "Roman Empire", "Byzantine Empire", "Greek Empire"},
                {"Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"},
                {"Mayflower", "Santa Maria", "Nina", "Speedwell"},
                {"Battle of Britain", "Battle of Normandy", "Battle of Stalingrad", "Battle of Gettysburg"},
                {"Nikita Khrushchev", "Leonid Brezhnev", "Mikhail Gorbachev", "Joseph Stalin"},
                {"Ferdinand Magellan", "Marco Polo", "Vasco da Gama", "Christopher Columbus"},
                {"1987", "1989", "1991", "1993"},
                {"Marie Curie", "Ada Lovelace", "Rosalind Franklin", "Dorothy Crowfoot Hodgkin"},
                {"Athens", "Rome", "Pompeii", "Troy"},
                {"Sun Tzu", "Laozi", "Mencius", "Zhuangzi"},
                {"Susan B. Anthony", "Elizabeth Cady Stanton", "Lucy Stone", "Alice Paul"},
                {"World War I", "World War II", "Korean War", "Vietnam War"},
                {"HMS Beagle", "HMS Bounty", "HMS Victory", "HMS Endurance"},
                {"Christopher Columbus", "Amerigo Vespucci", "Ferdinand Magellan", "John Cabot"},
                {"Treaty of Versailles", "Treaty of Tordesillas", "Treaty of Paris", "Treaty of Rome"},
                {"Elizabeth I", "Mary I", "Victoria", "Anne"},
                {"Cleopatra", "Nefertiti", "Hatshepsut", "Nefertari"},
                {"Renaissance", "Enlightenment", "Reformation", "Industrial Revolution"},
                {"Neil Armstrong", "Buzz Aldrin", "John Glenn", "Alan Shepard"},
                {"Abraham Lincoln", "Ulysses S. Grant", "Andrew Johnson", "Thomas Jefferson"},
                {"Florence Nightingale", "Clara Barton", "Mary Seacole", "Dorothea Dix"},
                {"1776", "1787", "1791", "1804"},
                {"Confucius", "Laozi", "Mencius", "Sun Tzu"},
        };

        public static String correctAnswers[] = {
                "Tutankhamun",
                "Augustus",
                "Assassination of Archduke Franz Ferdinand",
                "Mahatma Gandhi",
                "Incas",
                "RMS Titanic",
                "United Kingdom",
                "Genghis Khan",
                "King John",
                "1492",
                "Friedrich Engels",
                "American Civil War",
                "Amelia Earhart",
                "Stock Market Crash of 1929",
                "I Have a Dream",
                "Nicholas II",
                "Babylonians",
                "Ottoman Empire",
                "George Washington",
                "Mayflower",
                "Battle of Stalingrad",
                "Nikita Khrushchev",
                "Ferdinand Magellan",
                "1989",
                "Marie Curie",
                "Pompeii",
                "Sun Tzu",
                "Susan B. Anthony",
                "World War II",
                "HMS Beagle",
                "Christopher Columbus",
                "Treaty of Versailles",
                "Elizabeth I",
                "Cleopatra",
                "Renaissance",
                "Neil Armstrong",
                "Abraham Lincoln",
                "Florence Nightingale",
                "1776",
                "Confucius"
        };
    }


    public static class Trivia {
        public static String questions[] = {
                "What is the largest planet in our solar system?",
                "Which planet is known as the 'Red Planet'?",
                "Which country is famous for its tulips and windmills?",
                "Who is the lead singer of the band U2?",
                "Which gas do plants absorb from the atmosphere during photosynthesis?",
                "What is the largest mammal in the world?",
                "What is the smallest prime number?",
                "What is the main component of Earth's core?",
                "In which year did the Titanic sink?",
                "What is the chemical symbol for gold?",
                "What is the capital of Japan?",
                "Who wrote the play 'Romeo and Juliet'?",
                "What is the chemical symbol for water?",
                "Which gas makes up the majority of Earth's atmosphere?",
                "What is the largest organ in the human body?",
                "What is the highest mountain in the world?",
                "Who is the author of 'To Kill a Mockingbird'?",
                "What is the chemical symbol for oxygen?",
                "What is the chemical symbol for silver?",
                "Who is known as the 'Father of Modern Physics'?",
                "Which country is famous for its pyramids, including the Great Pyramid of Giza?",
                "What is the chemical symbol for carbon?",
                "What is the chemical symbol for sodium?",
                "What is the chemical symbol for nitrogen?",
                "What is the smallest planet in our solar system?",
                "Who is the author of '1984'?",
                "What is the chemical symbol for lead?",
                "What is the largest bone in the human body?",
                "Who painted the 'Mona Lisa'?",
                "What is the capital of Australia?",
                "Which gas is used by plants during photosynthesis to produce glucose?",
                "What is the chemical symbol for iron?",
                "Which famous scientist developed the theory of general relativity?",
                "What is the largest internal organ in the human body?",
                "Which gas is responsible for the ozone layer in Earth's atmosphere?",
                "What is the chemical symbol for potassium?",
                "What is the smallest continent by land area?",
                "What is the highest mountain in North America?",
                "What is the chemical symbol for copper?",
                "In which European city is the famous Eiffel Tower located?",
                "What is the chemical symbol for helium?",
        };

        public static String choices[][] = {
                {"Jupiter", "Saturn", "Mars", "Venus"},
                {"Mars", "Venus", "Mercury", "Saturn"},
                {"Netherlands", "Belgium", "Germany", "Denmark"},
                {"Bono", "Chris Martin", "Bruce Springsteen", "Mick Jagger"},
                {"Oxygen", "Carbon dioxide", "Nitrogen", "Carbon monoxide"},
                {"Blue whale", "Elephant", "Giraffe", "Hippopotamus"},
                {"1", "2", "3", "5"},
                {"Iron", "Gold", "Copper", "Nickel"},
                {"1912", "1920", "1915", "1917"},
                {"Au", "Ag", "Fe", "Hg"},
                {"Tokyo", "Beijing", "Seoul", "Bangkok"},
                {"William Shakespeare", "Charles Dickens", "Jane Austen", "George Orwell"},
                {"H2O", "He", "CO2", "N2"},
                {"Nitrogen", "Oxygen", "Carbon dioxide", "Argon"},
                {"Skin", "Liver", "Heart", "Brain"},
                {"Mount Everest", "K2", "Kangchenjunga", "Lhotse"},
                {"Harper Lee", "J.K. Rowling", "George Orwell", "Mark Twain"},
                {"O2", "H2O", "CO2", "N2"},
                {"Ag", "Au", "Fe", "Hg"},
                {"Albert Einstein", "Isaac Newton", "Galileo Galilei", "Stephen Hawking"},
                {"Egypt", "Greece", "Mexico", "Italy"},
                {"C", "O2", "CO2", "N2"},
                {"Na", "K", "Fe", "Cu"},
                {"N2", "O2", "H2O", "CO2"},
                {"Mercury", "Venus", "Mars", "Jupiter"},
                {"George Orwell", "Aldous Huxley", "Ray Bradbury", "J.R.R. Tolkien"},
                {"Pb", "Fe", "Ag", "Cu"},
                {"Femur", "Tibia", "Fibula", "Radius"},
                {"Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"},
                {"Canberra", "Sydney", "Melbourne", "Perth"},
                {"Oxygen", "Carbon dioxide", "Nitrogen", "Methane"},
                {"Fe", "Ag", "Au", "Hg"},
                {"Albert Einstein", "Isaac Newton", "Galileo Galilei", "Stephen Hawking"},
                {"Liver", "Heart", "Brain", "Lung"},
                {"O3", "N2", "CO2", "H2O"},
                {"K", "N2", "H2O", "O2"},
                {"Australia", "Antarctica", "South America", "Africa"},
                {"Denali", "Kilimanjaro", "Aconcagua", "Mont Blanc"},
                {"Cu", "Ag", "Fe", "Au"},
                {"Paris", "London", "Berlin", "Madrid"},
                {"He", "N2", "O2", "Ar"},
        };

        public static String correctAnswers[] = {
                "Jupiter",
                "Mars",
                "Netherlands",
                "Bono",
                "Carbon dioxide",
                "Blue whale",
                "2",
                "Iron",
                "1912",
                "Au",
                "Tokyo",
                "William Shakespeare",
                "H2O",
                "Nitrogen",
                "Skin",
                "Mount Everest",
                "Harper Lee",
                "O2",
                "Ag",
                "Albert Einstein",
                "Egypt",
                "C",
                "Na",
                "N2",
                "Mercury",
                "George Orwell",
                "Pb",
                "Femur",
                "Leonardo da Vinci",
                "Canberra",
                "Oxygen",
                "Fe",
                "Albert Einstein",
                "Liver",
                "O3",
                "K",
                "Australia",
                "Denali",
                "Cu",
                "Paris",
                "He",
        };
    }
    public static class Geography {
        public static String questions[] = {
                "What is the capital of France?",
                "Which river is the longest in the world?",
                "In which country can you find the Great Barrier Reef?",
                "Which mountain range stretches across Switzerland, France, and Italy?",
                "What is the largest desert in the world?",
                "Which continent is known as the 'Land Down Under'?",
                "What is the capital of Japan?",
                "Which country is known as the 'Land of a Thousand Lakes'?",
                "The Amazon Rainforest is primarily located in which continent?",
                "What is the highest mountain in North America?",
                "Which African country is known as the 'Rainbow Nation'?",
                "What is the largest ocean in the world?",
                "In which U.S. state can you find the Grand Canyon?",
                "What is the capital of Brazil?",
                "Which river flows through Egypt and Sudan?",
                "Which European city is divided into two separate countries, Buda and Pest?",
                "What is the northernmost capital city in the world?",
                "In which country can you visit the ancient city of Petra?",
                "Which African country is home to the Sahara Desert?",
                "What is the smallest country in the world by land area?",
                "The Great Wall of China is located in which province of China?",
                "Which U.S. state is known as the 'Sunshine State'?",
                "What is the largest lake in Africa?",
                "Which country is known for its fjords, such as the Geirangerfjord and Nærøyfjord?",
                "What is the largest country in South America?",
                "Which river is the second longest in Africa and flows through multiple countries including Uganda and Sudan?",
                "What is the highest mountain in the world?",
                "In which country can you find the city of Marrakech and the Atlas Mountains?",
                "What is the capital of Russia?",
                "Which island nation is also known as the 'Pearl of the Indian Ocean'?",
                "Which African country is home to the Serengeti National Park and Mount Kilimanjaro?",
                "What is the smallest continent by land area?",
                "Which country is known as the 'Land of Fire and Ice'?",
                "What is the capital of Canada?",
                "Which river flows through Cairo, the capital of Egypt?",
                "In which European country can you find the city of Barcelona and the Pyrenees Mountains?",
                "Which U.S. state is famous for its volcanoes and the Hana Highway?",
                "What is the largest island in the Mediterranean Sea?",
                "Which country is known for its stunning fjords, including the Nærøyfjord and the Sognefjord?",
                "What is the longest river in South America?",
                "In which country can you find the ancient city of Angkor Wat?",
                "Which African country is known as the 'Land of a Thousand Hills'?",
        };

        public static String choices[][] = {
                {"Berlin", "Paris", "Madrid", "Rome"},
                {"Amazon River", "Nile River", "Mississippi River", "Yangtze River"},
                {"Australia", "Indonesia", "Thailand", "Philippines"},
                {"Rocky Mountains", "Andes", "Himalayas", "Alps"},
                {"Gobi Desert", "Sahara Desert", "Atacama Desert", "Kalahari Desert"},
                {"Asia", "Africa", "Australia", "South America"},
                {"Tokyo", "Beijing", "Seoul", "Bangkok"},
                {"Sweden", "Finland", "Norway", "Iceland"},
                {"South America", "Africa", "Asia", "North America"},
                {"Mount St. Helens", "Mount Everest", "Denali", "Mount Kilimanjaro"},
                {"Nigeria", "South Africa", "Ghana", "Kenya"},
                {"Indian Ocean", "Atlantic Ocean", "Pacific Ocean", "Arctic Ocean"},
                {"Nevada", "Arizona", "Colorado", "New Mexico"},
                {"Brasília", "São Paulo", "Rio de Janeiro", "Buenos Aires"},
                {"Nile River", "Amazon River", "Mississippi River", "Yangtze River"},
                {"Berlin", "Vienna", "Budapest", "Prague"},
                {"Reykjavik", "Stockholm", "Helsinki", "Oslo"},
                {"Jordan", "Egypt", "Lebanon", "Iraq"},
                {"Morocco", "Algeria", "Tunisia", "Libya"},
                {"Vatican City", "Monaco", "San Marino", "Malta"},
                {"Hubei", "Shaanxi", "Jiangsu", "Heilongjiang"},
                {"California", "Florida", "Texas", "Hawaii"},
                {"Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"},
                {"Norway", "Sweden", "Denmark", "Iceland"},
                {"Brazil", "Argentina", "Colombia", "Peru"},
                {"Nile River", "Congo River", "Niger River", "Zambezi River"},
                {"Mount Kilimanjaro", "Mount Everest", "Mount Fuji", "Mount McKinley"},
                {"Morocco", "Egypt", "Algeria", "Tunisia"},
                {"Moscow", "St. Petersburg", "Kiev", "Warsaw"},
                {"Maldives", "Seychelles", "Mauritius", "Madagascar"},
                {"Kenya", "Rwanda", "Uganda", "Tanzania"},
                {"Asia", "Australia", "Europe", "South America"},
                {"Iceland", "Ireland", "New Zealand", "Madagascar"},
                {"Ottawa", "Montreal", "Vancouver", "Toronto"},
                {"Nile River", "Amazon River", "Danube River", "Rhine River"},
                {"Spain", "France", "Portugal", "Italy"},
                {"California", "Alaska", "Hawaii", "Oregon"},
                {"Sardinia", "Sicily", "Cyprus", "Crete"},
                {"Norway", "Sweden", "Denmark", "Finland"},
                {"Amazon River", "Orinoco River", "Paraná River", "Magdalena River"},
                {"Cambodia", "Vietnam", "Laos", "Thailand"},
                {"Rwanda", "Uganda", "Burundi", "Kenya"},
        };

        public static String correctAnswers[] = {
                "Paris",
                "Nile River",
                "Australia",
                "Alps",
                "Sahara Desert",
                "Australia",
                "Tokyo",
                "Finland",
                "South America",
                "Denali",
                "South Africa",
                "Pacific Ocean",
                "Arizona",
                "Brasília",
                "Nile River",
                "Budapest",
                "Reykjavik",
                "Jordan",
                "Morocco",
                "Vatican City",
                "Hubei",
                "Florida",
                "Lake Victoria",
                "Norway",
                "Brazil",
                "Nile River",
                "Mount Everest",
                "Morocco",
                "Moscow",
                "Maldives",
                "Tanzania",
                "Australia",
                "Iceland",
                "Ottawa",
                "Nile River",
                "Spain",
                "Hawaii",
                "Sicily",
                "Norway",
                "Amazon River",
                "Cambodia",
                "Rwanda",
        };
    }

}
